theme = "tokyonight_storm"

[editor]
line-number = "relative"
true-color = true
mouse = false
scrolloff = 5
bufferline = 'always'
idle-timeout = 0
cursorline = true
auto-format = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.statusline]
left = ['mode', 'spinner']
center = ['file-name', 'version-control', 'read-only-indicator']
right = ['diagnostics','spacer', 'position', 'position-percentage', 'separator', 'file-encoding', 'file-line-ending', 'file-type']
separator = " │"
mode.normal = "normal"
mode.insert = "insert"
mode.select = "visual"

[editor.lsp]
display-messages = true

[keys.insert]
C-space = "signature_help"
C-s = ':w'

[keys.normal]
C-x = ':buffer-close'
H = ':buffer-previous'
L = ':buffer-next'
C-s = ':w'
C-f = ':fmt'
g = { t = ":goto 1" }
"C-+" = "increment"
"C-*"  = "decrement"
