[[language]]
name = "svelte"
scope = "source.svelte"
file-types = ["svelte"]
roots = ["tailwind.config.js","tailwind.config.cjs"]
language-servers = [ "tailwindcss-svelte", "svelteserver" ]

[language-server.tailwindcss-svelte]
language-id = "svelte"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { }

[[language]]
name = "css"
scope = "source.css"
file-types = ["css", "postcss"]
language-servers = [ "tailwindcss-css", "vscode-css-language-server" ]

[language-server.tailwindcss-css]
language-id = "css"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { }

[[language]]
name = "html"
scope = "text.html.basic"
file-types = ["html"]
language-servers = [ "tailwindcss-html", "vscode-html-language-server" ]
formatter = { command = '/Users/pdz/.bun/bin/prettier', args = ["--parser", "html"] }

[[language]]
name = "typescript"
formatter = { command = '/Users/pdz/.bun/bin/prettier', args = ["--parser", "typescript"] }


[language-server.tailwindcss-html]
language-id = "html"
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { }

[[language]]
name = "rust"
rulers = [100]

[[language]]
name = "v"
file-types = ["v", "vv"]

[[language]]
name = "verilog"
file-types = ["vh", "sh", "svh"]
